# Generated by Django 5.0.1 on 2024-01-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_field',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
